### ISSUE TITLE
CALCnet 2.2

### ISSUE THREAD

**Issue by Ivoah** [KermMartian/ArTICL#7]
Would it be okay if I added the CALCnet 2.2 protocol to ArTICL? I'd mostly be copypasta from gcnclient3

**Comment by KermMartian** [comment]
ArTICL is intended specifically for the TI link protocol, and making it easier to transfer the data types that the TI link protocol supports. CALCnet 2.2 would be a completely distinct codebase, and I don't think it makes sense to add it to ArTICL. The one exception might be if you wanted to add express support for the BASIC CALCnet libraries, since they transfer strings and lists, but I feel like even that is a bit outside the scope of ArTICL.

**Comment by Ivoah** [comment]
Alright, then would it be okay if I copypasta'd the functions from gcnclient3 into their own library? (Of course I'd give you all credit) Or better, you make a blank repo, and I'll just make PRs so that the repo is on your account

**Comment by KermMartian** [comment]
Apologies for the slow response. Perhaps an even better solution would be to abstract and modularize the CALCnet libraries within the gCn repo, and consider making that a general CALCnet repo?
